[package]
name = "cacher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
lru = "0.7.5"
rand = "0.8.5"
clap = { version = "3.1.17", features = ["derive"] }